version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: task-db
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
      POSTGRES_DB: taskmanager
    ports:
      - "5433:5432"
    volumes:
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-network


volumes:
  postgres_data:

networks:
  task-network:
    driver: bridge