version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: task-db
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
      POSTGRES_DB: taskmanager
    ports:
      - "5432:5432"
    volumes:
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-network

  backend:
    build: ./backend
    container_name: task-backend
    ports:
      - "3001:3001"
    environment:
      DB_HOST: postgres
      DB_USER: taskuser
      DB_PASSWORD: taskpass
      DB_NAME: taskmanager
      DB_PORT: 5432
    depends_on:
      - postgres
    networks:
      - task-network
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  task-network:
    driver: bridge